// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(State) {
  var PartialLocation = {};
  var PartialPath = {};
  var Transition = {};
  return {
          PartialLocation: PartialLocation,
          PartialPath: PartialPath,
          Transition: Transition
        };
}

var State = {};

var PartialLocation = {};

var PartialPath = {};

var Transition = {};

var $$History = {
  PartialLocation: PartialLocation,
  PartialPath: PartialPath,
  Transition: Transition
};

var BrowserHistoryOptions = {};

var MemoryHistoryOptions = {};

var HashHistoryOptions = {};

exports.Make = Make;
exports.State = State;
exports.$$History = $$History;
exports.BrowserHistoryOptions = BrowserHistoryOptions;
exports.MemoryHistoryOptions = MemoryHistoryOptions;
exports.HashHistoryOptions = HashHistoryOptions;
/* No side effect */
